name: PWS
favicon: null
layout_spectrum: 0.5258442324120551
typography_spectrum: 0.5654415246099234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24329170095734298
  lightness: 0.7251730510033667
  saturation: 0.8926031989976764
  rhythmicContrast: 0.5610934761352837
purpose: []
