favicon: null
name: PWS
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8926031989976764
  brandStrength: 0.243291700957343
  lightness: 0.7251730510033667
  brandColors:
    - '#04CFCD'
    - '#040505'
    - '#3C908F'
    - '#00424A'
    - '#008889'
  rhythmicContrast: 0.5610934761352837
typography_spectrum: 0.5404255
layout_spectrum: 0.5021276
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
